openapi: 3.0.0
info:
  title: Test API with Enums
  version: 1.0.0
paths:
  /test:
    get:
      operationId: test_get
      tags: [test]
      summary: Test endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
components:
  schemas:
    TestResponse:
      type: object
      properties:
        status:
          type: string
          enum: [active, inactive, pending]
          description: Status of the item
        type:
          type: string
          enum: [user, admin, guest]
          description: Type of user
        priority:
          type: string
          enum: [low, medium, high, critical]
          description: Priority level
